site_name: Abby's Doc Site Name  # 页签标题
docs_dir: docs                   # 文档目录
site_url: https://abby-cyber.github.io/docs

### Example Configuration ###

# Custom Homepage Elements
home_cover_image: images/Planetary-02150x.png # This path starts at your root mkdocs directory.
home_tagline: Abby's Doc Site
home_description: |
  This site is an example showcase for abby's documentation site.

# Gradient Color
home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: Docs                   # Comment this parameter out to remove the button.
home_button1_url: https://abby-cyber.github.io/master/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people                        # Options: "people", "gear", "image"
home_button1_blurb: |                            # Short description of this button / section.
  This joker navigates to the shadow wizard armory located in "/Folder1/index.md"

home_button2_name: Clicky2   # Comment this parameter out to remove the button.
home_button2_url: Page    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: |         # Short description of this button / section.
  This goober navigates to some important thingies located in "/Folder2/index.md"

# Homepage Code Execution
home_execute_js: | # Javascript to execute when accessing the homepage
  console.log("This is an example!");

theme: 
  name: material                 # material for mkdocs 自定义主题
  custom_dir: docs/overrides     # 自定义主题的目录
  features:
    - navigation.tabs            # 顶部导航栏的标签页
#    - navigation.path           # 顶部导航栏的路径，企业版才有
#    - navigation.sections        # 关闭顶部导航栏的下拉菜单，显示所有页面
    - navigation.expand          # 展开顶部导航栏的下拉菜单，当navigation.sections开启时不适用
    - toc.integrate              # 关闭右侧目录，显示在左侧的导航栏中
    - navigation.top             # back to top 按钮
    - search.suggest             # 搜索提示
    - search.highlight           # 搜索结果高亮
    - content.tabs.link          # Content tabs are linked based on their label, not offset. 
    - content.code.annotation    # 启用代码注释
    - content.code.copy          # 启用代码复制按钮
  language: en 
  palette:
    - scheme: abby 
      toggle:
        icon: material/brightness-4 
        name: Switch to dark mode
      # 见extra.css自定义主题颜色
      primary: custom 
      accent: purple
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: custom
      accent: pink

extra:
  social: # 底部社交链接，如twitter、github等
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin-in
  # 使用mike部署版本时，需要配置以下内容，并且需要配置site_url
  version:
    provider: mike
   
extra_css:
  - stylesheets/extra.css

# 在 YAML 中，| 符号用于表示一个字面块标量（literal block scalar）。
# 这种语法允许你在 YAML 文件中包含多行字符串，而无需使用引号或特殊的转义字符。
copyright: |  
  &copy; 2023 <a href="https://github.com/james-willett" target="_blank" rel="noopener">James Willett</a>

nav: 
  - Home: README.md
  - Page: Page.md
  - This is folder: 
      - folder2:
        - folderpage2: page-folder/folder2/folderpage2.md
      - folderpage1: page-folder/folderpage1.md
  - "External Link": https://www.baidu.com
