site_name: Abby's first MkDocs site
site_url: https://abby-cyber.github.io/
docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - content.action.edit
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

extra:
  version:
    provider: mike  

plugins:
  - search
  - mike

markdown_extensions:
  - meta


nav:
    - Home: index.md
    - About: about.md
    - Guide: 
      - Introduction: 
        - Overview: guide/introduction/index.md
        - Getting started: guide/introduction/getting-started.md
      - Installation: guide/installation.md
      - Usage: guide/usage.md
      - Configuration: guide/configuration.md
      - License: guide/license.md   