site_name: Abby's first MkDocs site
site_url: https://abby-cyber.github.io/docs/

theme:
  name: material
  custom_dir: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

nav:
    - Home: index.md
    - About: about.md
    - Guide: 
      - Introduction: 
        - Overview: guide/introduction/index.md
        - Getting started: guide/introduction/getting-started.md
      - Installation: guide/installation.md
      - Usage: guide/usage.md
      - Configuration: guide/configuration.md
      - License: guide/license.md   